# Generated by Django 4.1.5 on 2023-01-31 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, verbose_name='Наименование вещи')),
                ('description', models.TextField(verbose_name='Описание вещи')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Цена со скидкой')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='api.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Вещь',
                'verbose_name_plural': 'Вещи',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('user_contacts', models.CharField(max_length=127)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('one_size', 'one_size'), ('xl', 'xl'), ('l', 'l'), ('m', 'm'), ('s', 's'), ('xs', 'xs')], max_length=10, verbose_name='Размер')),
            ],
            options={
                'verbose_name': 'Размер',
                'verbose_name_plural': 'Размеры',
            },
        ),
        migrations.CreateModel(
            name='SizeItemCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_count', models.IntegerField(verbose_name='Количество')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sizes_count', to='api.item', verbose_name='Вещь')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_count', to='api.size', verbose_name='Размер')),
            ],
            options={
                'verbose_name': 'Количество вещи с размером',
                'verbose_name_plural': 'Количество вещи с размером',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('one_size', 'one_size'), ('xl', 'xl'), ('l', 'l'), ('m', 'm'), ('s', 's'), ('xs', 'xs')], max_length=10, verbose_name='Размер')),
                ('item_count', models.IntegerField(verbose_name='Количество')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='api.item', verbose_name='Вещь')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='api.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Вещь в заказе',
                'verbose_name_plural': 'Вещи в заказе',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(through='api.OrderItem', to='api.item'),
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='item_images/%Y/%m/%d/', verbose_name='Картинка')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.item', verbose_name='Вещь')),
            ],
            options={
                'verbose_name': 'Иллюстрация вещи',
                'verbose_name_plural': 'Иллюстрации вещей',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='sizes',
            field=models.ManyToManyField(through='api.SizeItemCount', to='api.size'),
        ),
    ]
