# Generated by Django 4.1.5 on 2023-02-01 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_item_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sizeitemcount',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes_count', to='api.item', verbose_name='Вещь'),
        ),
    ]
