# Generated by Django 4.1.5 on 2023-02-02 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_orderitem_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('waiting', 'waiting'), ('created', 'created'), ('canceled', 'canceled'), ('done', 'done')], default='waiting', max_length=10, verbose_name='Статус'),
        ),
    ]
