# Generated by Django 4.1.5 on 2023-02-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.UUIDField(blank=True, null=True, verbose_name='ID платежа'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL платежа'),
        ),
    ]
